rng(0);
n=5000;
T=-1+2*rand(n);
z=sum(abs(T),2);
A=T+diag(z);
b=-1+2*rand(n,1);
x0=zeros(n,1);
iter=200;
t=tic;
xgauss=A\b;
tgauss=toc(t);
backdir=norm(b-A*xgauss);
t=tic;
[L,U,P]=lu(A);
y=L\(P*b);
xlu=U\y;
tlu=toc(t);
backlu=norm(b-A*xlu);
t=tic;
[xJ,residualJ]=helper.j(A,b,x0,iter);
tj=toc(t);
t=tic;
[xGS,residualGS]=helper.gs(A,b,x0,iter);
tgs=toc(t);
t=tic;
[xSOR,residualSOR]=helper.sor(A,b,x0,0.5,iter);
tsor=toc(t);
fprintf('Gauss= %.4fs, backwards error= %.4e\n',tgauss,backdir);
fprintf('LU= %.4fs, backwards error= %.4e\n',tlu,backlu);
fprintf('Jacobi= %.4fs, backwards error=%.4e\n',tj,norm(b-A*xJ));
fprintf('GS= %.4fs, backwards error=%.4e\n',tgs,norm(b-A*xGS));
fprintf('SOR= %.4fs, backwards error=%.4e\n',tsor,norm(b-A*xSOR));
figure;
plot(log(residualJ));
title('Jacobi');
xlabel('k');
grid on;
figure;
plot(log(residualGS));
title('Gauss-Seidel');
xlabel('k');
grid on;
figure;
plot(log(residualSOR));
title('SOR');
xlabel('k');
grid on;
iterJ=find(residualJ<=backdir,1);
iterGS=find(residualGS<=backdir,1);
iterSOR=find(residualSOR<=backdir,1);
fprintf(['Iterations to reach backwards error: Jacobi= %s, GS= %s, ' ...
    'SOR= %s\n'], num2str(iterJ), num2str(iterGS), num2str(iterSOR));